# Generated by Django 6.0.7 on 2026-07-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FirstAPP", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaivarity",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
