# Generated by Django 6.0.7 on 2026-07-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FirstAPP", "0002_chaivarity_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaivarity",
            name="price",
            field=models.TextField(default=""),
        ),
    ]
