# Generated by Django 6.0.7 on 2026-07-31 09:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChaiVarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="chais/")),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ML", "MASALA"),
                            ("GR", "GINGER"),
                            ("KI", "KIWI"),
                            ("KL", "PLAIN"),
                            ("EL", "ELAICHI"),
                        ],
                        max_length=3,
                    ),
                ),
            ],
        ),
    ]
